### ISSUE TITLE
MimeDetective::new() returns error on Arch Linux

### ISSUE THREAD

**Issue by cjbassi** [csharad/mime-detective#1]
So on Arch Linux, I have the `file` package installed which provides `/usr/share/file/misc/magic.mgc`, but it seems mime-detective is expecting the file to be located at `/usr/share/misc/magic.mgc`. Any ideas on how to fix this aside from symlinking? Thanks!

**Comment by pepsighan** [comment]
Added `MimeDetective::load_databases` which allows passing your own custom paths of the database.
You may have to update your deps to `mime-detective = "0.2.2"`.

Does it solve your problem?

**Comment by cjbassi** [comment]
Thanks for the quick response! And using `load_databases` with a custom path is working.

What about having mime-detective find the `magic.mgc` file itself when using `MimeDetective::new()`? Otherwise each app/library that uses mime-detective would have to implement that logic. So default to `/usr/share/misc/magic.mgc` and switch to `/usr/share/file/misc/magic.mgc` if on Arch Linux. Using Arch Linux can be detected by checking the `/etc/os-release` file which contains (for me):
```
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
```

**Comment by pepsighan** [comment]
Use `MimeDetective::load_databases` if `MimeDetective::new` fails for now. 

Since `new` panics when it is not able to find a particular magic file, it will be removed in the next version. 

As @cjbassi has pointed out, he is striving for a cross-platform way of creating reading mimes. Our options to implement such a feature as far as I can think would be to read the provided `.mgc` file at compile time. 

So, closing this issue as it is resolved.
